baseURL = "https://www.omochizo.netlify.app/"
languageCode = "ja"
title = "パケット畑でつかまえて"
theme = "m10c"
paginate = 5

[params]
    authod = "omochizou"
    description = " "
    avatar = "yoshi.png"
    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/omochiozu"
