baseURL = "https://omochizo.netlify.app/"
languageCode = "ja"
title = "パケット畑でつかまえて"
theme = "m10c"
paginate = 5

[params]
    authod = "omochizou"
    description = "ヒロアカと初音ミクが好きな趣味プログラマ"
    avatar = "yoshi.png"
    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/omochizou"
